name: NFT Syndicates QA

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: |
        npm install
        npx hardhat compile

    - name: Run Smart Contract Tests
      run: npx hardhat test

    - name: Run Frontend Tests
      run: npx playwright test
